In [1]:
import numpy as np

In [10]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d)
print(arr_1d.dtype)

[1 2 3 4 5]
int64


In [6]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
zeros = np.zeros((3, 4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
range_arr = np.arange(0, 10, 2)
print(ra)

[ 0  2  4  6  8 10]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [4]:


arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [6]:
zeros = np.zeros((3, 5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [7]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]
